# Generated by Django 5.1.1 on 2024-10-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(default='+998911234567', max_length=150),
            preserve_default=False,
        ),
    ]
